"""
Trading strategy logic for two-sided weather market trading.

Evaluates brackets based on temperature, time of day, and distance from current temp
to decide when to buy YES (bracket likely to hit) or NO (bracket unlikely to hit).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, time
from typing import Optional

from config.settings import TRADING, STATIONS
from engine.bracket_tracker import Bracket
from exchange.kalshi_client import MarketPrice

logger = logging.getLogger(__name__)


@dataclass
class TradingSignal:
    """A trading signal generated by strategy evaluation."""

    action: str  # 'BUY_YES', 'BUY_NO', 'SKIP', 'HOLD'
    bracket: Bracket
    price_cents: int  # Price we'd pay
    contracts: int  # How many contracts
    reason: str  # Why we're taking this action
    skip_reason: Optional[str] = None


class TradingStrategy:
    """
    Encapsulates all trading logic and decision-making.

    Uses temperature-based heuristics to estimate bracket probability,
    then compares to market prices to find mispricing.
    """

    def __init__(self):
        pass

    def evaluate_bracket_opportunity(
        self,
        bracket: Bracket,
        current_temp_f: float,
        daily_max_f: float,
        current_bracket_index: int,
        local_time: datetime,
        market_price: MarketPrice,
        portfolio,
    ) -> TradingSignal:
        """
        Evaluate whether to trade a specific bracket.

        Args:
            bracket: The bracket to evaluate
            current_temp_f: Current temperature
            daily_max_f: Daily maximum so far
            current_bracket_index: Index of bracket containing daily max
            local_time: Current local time
            market_price: Current market prices
            portfolio: Portfolio for position sizing

        Returns:
            TradingSignal with recommended action
        """
        # Calculate distance from daily max to this bracket
        distance = self._calculate_bracket_distance(bracket, daily_max_f)

        # Get time-of-day factor (warming vs. cooling phase)
        time_factor = self._get_time_factor(local_time)

        # Estimate probability this bracket will be hit
        probability = self._estimate_bracket_probability(
            bracket,
            current_bracket_index,
            daily_max_f,
            distance,
            time_factor,
        )

        # Generate signal based on probability vs. market price
        return self._generate_signal(
            bracket,
            probability,
            market_price,
            portfolio,
            distance,
            time_factor,
        )

    def _calculate_bracket_distance(self, bracket: Bracket, daily_max_f: float) -> float:
        """
        Calculate distance in degrees from daily max to bracket.

        Returns:
            Positive if bracket is above daily max, negative if below
        """
        if bracket.lower_f is None:
            # Open-ended low bracket
            return bracket.upper_f - daily_max_f
        elif bracket.upper_f is None:
            # Open-ended high bracket
            return bracket.lower_f - daily_max_f
        else:
            # Middle bracket - distance to lower bound
            return bracket.lower_f - daily_max_f

    def _get_time_factor(self, local_time: datetime) -> float:
        """
        Get time-of-day factor.

        Returns:
            1.0 = peak warming period (noon-2pm)
            0.5 = morning warming (6am-noon)
            0.0 = cooling period (after 4pm)
            -0.5 = evening (after 6pm)
        """
        hour = local_time.hour

        if 12 <= hour < 14:
            return 1.0  # Peak warming
        elif 6 <= hour < 12:
            return 0.5  # Morning warming
        elif 14 <= hour < 16:
            return 0.3  # Afternoon (starting to cool)
        elif 16 <= hour < 18:
            return 0.0  # Cooling
        else:
            return -0.5  # Evening (temperatures falling)

    def _estimate_bracket_probability(
        self,
        bracket: Bracket,
        current_bracket_index: int,
        daily_max_f: float,
        distance_f: float,
        time_factor: float,
    ) -> float:
        """
        Estimate probability (0-100) that this bracket will be hit.

        Heuristic based on:
        - Distance from current daily max
        - Time of day (warming vs cooling)
        - Whether we've already crossed this bracket
        """
        # If we're already in this bracket or passed it
        if bracket.index == current_bracket_index:
            return 95.0  # Very high probability

        if bracket.index < current_bracket_index:
            # Lower bracket - already crossed
            return 99.0  # Almost certain (won't go back down)

        # Higher bracket - not yet reached
        if distance_f < 0:
            # Already above this bracket
            return 99.0

        # Not yet reached - depends on distance and time
        if distance_f <= 2.0 and time_factor >= 0.5:
            # Very close and still warming
            return 70.0
        elif distance_f <= 4.0 and time_factor >= 0.3:
            # Moderate distance, still some warming potential
            return 40.0
        elif distance_f > 6.0:
            # Far away
            if time_factor <= 0:
                return 5.0  # Cooling, unlikely
            else:
                return 15.0  # Warming but far
        else:
            # 4-6 degrees away
            if time_factor > 0:
                return 25.0
            else:
                return 10.0

    def _generate_signal(
        self,
        bracket: Bracket,
        probability: float,
        market_price: MarketPrice,
        portfolio,
        distance_f: float,
        time_factor: float,
    ) -> TradingSignal:
        """
        Generate a trading signal based on estimated probability vs market price.

        Logic:
        - If probability is high but YES price is low → BUY YES
        - If probability is low but NO price is low → BUY NO
        - Otherwise SKIP
        """
        yes_price = market_price.yes_price_cents
        no_price = market_price.no_price_cents

        # Check if bracket is likely (high probability)
        if probability >= 60:
            # Likely to hit - consider buying YES
            if yes_price < TRADING.yes_entry_current_bracket_max:
                # Good price for likely bracket
                contracts = portfolio.calculate_position_size(
                    yes_price_cents=yes_price,
                    max_contracts=TRADING.max_contracts_per_trade,
                    risk_percent=TRADING.risk_percent_per_trade,
                )
                if contracts > 0:
                    return TradingSignal(
                        action="BUY_YES",
                        bracket=bracket,
                        price_cents=yes_price,
                        contracts=contracts,
                        reason=f"High probability ({probability:.0f}%) at good price ({yes_price}¢)",
                    )

            return TradingSignal(
                action="SKIP",
                bracket=bracket,
                price_cents=0,
                contracts=0,
                reason="",
                skip_reason=f"YES price too high ({yes_price}¢ >= {TRADING.yes_entry_current_bracket_max}¢)",
            )

        elif probability <= 20:
            # Unlikely to hit - consider buying NO
            if no_price < TRADING.no_entry_far_bracket_max:
                # Good price for unlikely bracket
                contracts = portfolio.calculate_position_size(
                    yes_price_cents=no_price,
                    max_contracts=TRADING.max_contracts_per_trade,
                    risk_percent=TRADING.risk_percent_per_trade,
                )
                if contracts > 0:
                    return TradingSignal(
                        action="BUY_NO",
                        bracket=bracket,
                        price_cents=no_price,
                        contracts=contracts,
                        reason=f"Low probability ({probability:.0f}%) at good NO price ({no_price}¢)",
                    )

            return TradingSignal(
                action="SKIP",
                bracket=bracket,
                price_cents=0,
                contracts=0,
                reason="",
                skip_reason=f"NO price too high ({no_price}¢ >= {TRADING.no_entry_far_bracket_max}¢)",
            )

        # Moderate probability - no clear edge
        return TradingSignal(
            action="SKIP",
            bracket=bracket,
            price_cents=0,
            contracts=0,
            reason="",
            skip_reason=f"Moderate probability ({probability:.0f}%), no clear edge",
        )

    def should_exit_position(
        self,
        position_db: dict,
        current_price: MarketPrice,
    ) -> tuple[bool, str]:
        """
        Determine if we should exit a position.

        Args:
            position_db: Position dict from database
            current_price: Current market price

        Returns:
            (should_exit, reason)
        """
        side = position_db["side"]
        entry_price = position_db["entry_price_cents"]
        contracts = position_db["contracts"]

        # Get current price for our side
        if side == "YES":
            current_side_price = current_price.yes_price_cents
        else:
            current_side_price = current_price.no_price_cents

        # Calculate gain/loss
        gain_cents = current_side_price - entry_price
        gain_percent = (gain_cents / entry_price) * 100 if entry_price > 0 else 0

        # Take profit conditions
        if gain_cents >= TRADING.take_profit_cents:
            return True, f"take_profit_cents (+{gain_cents}¢)"

        if gain_percent >= TRADING.take_profit_percent:
            return True, f"take_profit_percent (+{gain_percent:.1f}%)"

        if current_side_price >= TRADING.lock_profit_price:
            return True, f"lock_profit_price ({current_side_price}¢ >= {TRADING.lock_profit_price}¢)"

        # Stop loss conditions
        if gain_percent <= -TRADING.stop_loss_percent:
            return True, f"stop_loss ({gain_percent:.1f}% loss)"

        # No exit condition met
        return False, ""
